source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'jbuilder', '~> 2.0'
gem 'rest-client'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'spring'
  gem 'rspec-rails', '~> 3.1'
  gem 'database_cleaner'
end
